name: Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10  # Maximum runtime
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        check-latest: true
        
    - name: Debug system info
      run: |
        echo "Python version:"
        python --version
        echo "Pip version:"
        pip --version
        echo "System info:"
        uname -a
        echo "Disk space:"
        df -h
        echo "Memory info:"
        free -h
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install mediapipe==0.10.21
        pip install -r requirements.txt
        
    - name: Verify installation
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        export DISPLAY=:99
        echo "Testing MediaPipe installation..."
        python -c "import mediapipe as mp; print('MediaPipe version:', mp.__version__)"
        echo "Testing OpenCV installation..."
        python -c "import cv2; print('OpenCV version:', cv2.__version__)"
        echo "Testing NumPy installation..."
        python -c "import numpy; print('NumPy version:', numpy.__version__)"
        echo "All core dependencies verified successfully!"
      env:
        PYTHONPATH: ${{ github.workspace }}
        PYTHONUNBUFFERED: 1 