name: Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        sudo apt-get install -y portaudio19-dev
        sudo apt-get install -y libsndfile1
        sudo apt-get install -y libgl1-mesa-glx  # MediaPipe için OpenGL
        sudo apt-get install -y libglib2.0-0     # MediaPipe için GLib
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # MediaPipe için özel kurulum
        pip install mediapipe==0.10.21
        # Diğer bağımlılıklar
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 black
        
    - name: Verify MediaPipe installation
      run: |
        python -c "import mediapipe as mp; print('MediaPipe version:', mp.__version__)"
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Check formatting with black
      run: |
        black . --check
        
    - name: Run tests
      run: |
        pytest tests/ --cov=src/ --cov-report=term-missing
      env:
        PYTHONPATH: ${{ github.workspace }}
        # MediaPipe için gerekli environment variables
        PYTHONUNBUFFERED: 1
        TF_CPP_MIN_LOG_LEVEL: 2  # TensorFlow logging'i azalt
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 